### ISSUE TITLE
Not available via Wordpress plugins repository?

### ISSUE THREAD

**Issue by clarkewd** [Digital-Innovation-Lab/dhpress#3]
Just curious - is there a reason this plugin is not available in the Wordpress plugins repository? It is free and fairly easy
to add a plugin. See https://wordpress.org/plugins/about/ and https://wordpress.org/plugins/about/svn/ for more details.

**Comment by gaelicmichael** [comment]
I submitted it once and they didn't like the naming convention I used. I haven't gotten around to resubmitting it since then, though it's somewhere on my TO DO list.

**Comment by kvnjcby** [comment]
DH Press is now available in the Wordpress plugin repository at https://wordpress.org/plugins/dh-press/
